#!/usr/bin/env bash
pfurl --verb POST --raw --http $1/api/v1/cmd --jsonwrapper 'payload' --msg \
 '{  "action": "hello",
         "meta": {
                 "askAbout":     "sysinfo",
                 "echoBack":     "Hi there!"
         }
 }' --quiet --jsonpprintindent 4 --authToken password
